config/routes.rb
Rails.application.routes.draw do
  root 'epicenter#feed'
  get 'show_user' => 'epicenter#show_user'
  get 'following' => 'epicenter#following'
  get 'unfollow' => 'epicenter#unfollow'
  get 'tag_tweets' => 'epicenter#tag_tweets'

  resources :tweets
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :tweet_tags
    has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    belongs_to :user

    
    validates :message, presence: true
    before_validation :link_check, on: :create
    validates :message, length: {maximum: 150, too_long: " - if you need more than 250 characters, write a blog."}, on: :create
    after_validation :apply_link, on: :create
    

    has_many :tweet_tags
    has_many :tags, through: :tweet_tags


  private
    def link_check
      if self.message.include? "https://"
        arr = self.message.split
        indx = arr.map { |x| x.include? "https://" }.index(true)
        self.link = arr[indx]

          if arr[indx].length > 23
            arr[indx] = "#{arr[indx][0..20]}..."
          end

        self.message = arr.join(" ")
      end
    end

    def apply_link
      arr = self.message.split
      indx = arr.map { |x| x.include? "https://" }.index(true)
      if indx
        url = arr[indx]

        arr[indx] = "<a href='#{self.link}' target='_blank'>#{url}</a>"
      end
      self.message = arr.join(" ")
    end
end

app/models/tweet_tag.rb
class TweetTag < ApplicationRecord
  belongs_to :tweet
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tweets
  serialize :following, Array

  mount_uploader :avatar, AvatarUploader

  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys:[:name, :username, :bio, :location, :avatar, :following])
		devise_parameter_sanitizer.permit(:account_update, keys:[:name, :username, :bio, :location, :avatar, :following])
	end
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController

    # before_action :authenticate_user!

  def tag_tweets
    @tag = Tag.find(params[:id])
  end

  def feed
    @following_tweets = []

    Tweet.all.each do |tweet|
      if current_user.following.include?(tweet.user_id) || current_user.id == tweet.user_id
            @following_tweets.push(tweet)
      end
    end
  end

  def show_user
    @user = User.find(params[:id])
  end

  def following
    current_user.following.push(params[:id].to_i)
    current_user.save
    redirect_to show_user_path(id: params[:id])
  end

  def unfollow
    current_user.following.delete(params[:id].to_i)
    current_user.save
    redirect_to show_user_path(id: params[:id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!

  include TweetsHelper

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.create(tweet_params)

    @tweet = get_tagged(@tweet)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper

  def get_tagged(tweet)
    #Looking for tags... split will split tweet array into individual words
    message_arr = @tweet.message.split
    message_arr.each_with_index do |word, index|
      #create a new instance of Tag
      if word[0] == "#"
        if Tag.pluck(:phrase).include?(word.downcase)
          #save that tag as a variable
          tag = Tag.find_by(phrase: word.downcase)
        else
          #else, create a new tag
          tag = Tag.create(phrase: word.downcase)
        end
        
      tweet_tag = TweetTag.create(tweet_id: @tweet.id, tag_id: tag.id)

      message_arr[index] = "<a href='/tag_tweets?id=#{tag.id}'>#{word}</a>"
      end
    end

    @tweet.update(message: message_arr.join(" "))
    return tweet
  end

end

app/views/epicenter/feed.html.erb
<!-- <h1>@<%= current_user.username %>'s Twitter Feed</h1>

<p>Here's what your friends are saying...</p> <br> -->

<div class="d-flex">
  <div class="col-md-3">
    <div class="card-left">
      <div class="left-card-blue"></div>
      <%= image_tag current_user.avatar.url, class: 'rounded-circle', id: 'profile-pic' %>
      <div class="text-center">  
        <h4 class="username-left"><%= current_user.name %></h4>
        <p class="text-muted">@<%= current_user.username %></p>
      </div>
      <div class="row m-auto">
        <p class="col-md-4 profile-stats">Tweets</p>
        <p class="col-md-4 profile-stats">Following</p>
        <p class="col-md-4 profile-stats">Followers</p>
      </div>
      <div class="row m-auto">
        <p class="col-md-4 profile-stats-num">212</p>
        <p class="col-md-4 profile-stats-num">102</p>
        <p class="col-md-4 profile-stats-num">34</p>
      </div>
    </div>
  </div>


  <div class="col-md-6 p-0">
    <div class="home-tweet-box">
      <%= image_tag current_user.avatar.url, class: 'rounded-circle', id: 'nav-profile-pic' %>
      <input type="text" class="tweet-input" placeholder="What's happening?"><span class="insert-pic glyphicon glyphicon-picture"></span>
    </div>

    
      <% @following_tweets.each do |tweet| %>
        <div class="card tweet">
          <%= image_tag current_user.avatar.url, class: 'rounded-circle', id: 'tweet-profile-pic' %>
            <div class="tweet-content">
              <p class="mb-1"><span style="font-weight: bold"><%= tweet.user.name %></span>
                @<%= link_to tweet.user.username, show_user_path(id: tweet.user.id) %> &bull; <%= time_ago_in_words(tweet.created_at) %></p>
              <p><%= tweet.message.html_safe %></p>
            </div>
        </div>
      <% end %>
  </div>

</div>

app/views/epicenter/following.html.erb
<h1>Epicenter#following</h1>
<p>Find me in app/views/epicenter/following.html.erb</p>

app/views/epicenter/show_user.html.erb
<h1>@<%= @user.username %>'s Profile & Tweets</h1>

<p>
    <%= @user.name %>
</p>

<p>
    <%= @user.location %>
</p>

<p>
    <%= @user.bio %>
</p>

<p>
    <% if current_user.following.include?(@user.id) %>
            <%= link_to "Following", unfollow_path(id: @user.id), class: "btn btn-light", id: "unfollow-btn" %>
        <% else %>
            <% if current_user.id != @user.id %>
                <%= link_to "Follow", following_path(id: @user.id), class: "btn btn-success" %>
            <% end %>
    <% end %>    
</p>

<% @user.tweets.each do |tweet| %>
    <p>@<%= link_to @user.username, show_user_path(id: tweet.user.id) %> <%= time_ago_in_words(tweet.created_at)%> ago</p>
    <p><%= tweet.message.html_safe %></p>
<% end %>

app/views/epicenter/tag_tweets.html.erb
<h1><%= @tag.phrase %></h1>

<% @tag.tweets.order(created_at: :desc).each do |tweet| %>
  <%= tweet.user.name %> <%= link_to "@#{tweet.user.username}", show_user_path(id: tweet.user.id) %>
  &bull; <%= time_ago_in_words(tweet.created_at)%> ago

  <%= tweet.message.html_safe %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TTS Twitter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li>
                    <%= link_to root_path do %>
                    <span class="navbar-link"><i class="fas fa-home"></i> Home</span>
                    <% end %>
                </li>

                 <li>   
                    <%= link_to new_tweet_path do %>
                    <span class="navbar-link"><i class="fas fa-bolt"> Moments</i></span>
                    <% end %>
                </li>

                <li>   
                    <%= link_to new_tweet_path do %>
                    <span class="navbar-link"><i class="far fa-bell"> Notifications</i></span>
                    <% end %>
                </li>

                <li>   
                    <%= link_to new_tweet_path do %>
                    <span class="navbar-link"><i class="fas fa-envelope"> Messages</i></span>
                    <% end %>
                </li>
            </ul>
            <ul class="navbar-nav mx-auto">
                <li>
                    <i class="fab fa-twitter bird-icon"></i>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li><form class="navbar-form navbar-right mt-2">
                <input type="text" class="form-control nav-search" placeholder="Search Twitter">
                <span class="nav-search-icon fas fa-search"></span></li>
                
                <% if user_signed_in? %>
                    <li class="nav-item dropdown">
                        <a class="nav-link" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <% if current_user.avatar.blank? == false %>
                                <%= image_tag current_user.avatar.url, size:32, class: 'rounded-circle hand'%>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
                                    <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                                </div>
                            <% end %>
                            <li>
                                <%= link_to new_tweet_path do %>
                                <button class="btn tweet-button mt-1">Tweet</button>
                                <% end %>
                            </li>
                        </a>
                    </li>
                <% end %>
            </ul>
        </div>
    </nav>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_area :message, placeholder: "Whatcha thinkin?" %>
  </div>

  <div class="form-group">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit 'Tweet', class: 'btn btn-blue' %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Tweets</h1>

<table>
<!--   <thead class="text-center">
    <tr>
      <th>User</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead> -->

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td>
          <% unless tweet.user.avatar.url == nil %>
            <%= image_tag tweet.user.avatar.url, size: 35, class: 'rounded-circle' %> 
          <% end %>
          <b>@<%= link_to tweet.user.username, show_user_path(id: tweet.user.id) %></b></td>
        <td><%= tweet.message.html_safe %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Delete', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Tweet', new_tweet_path, class: "btn btn-primary text-white tweet-btn" %>

app/views/tweets/new.html.erb
<div class="d-flex">
  <div class="mx-auto">
    <h4 class="text-center">Compose New Tweet</h4>

    <%= render 'form', tweet: @tweet %>

    <%= link_to 'Back', tweets_path %>
  </div>
</div>

app/views/tweets/show.html.erb
<p>
  <strong>User:</strong>
  <%= link_to @tweet.user.username, show_user_path(id: @tweet.user.id) %>
</p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message.html_safe %>
</p>


<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>